[project]
name = "home-infrastructure"
version = "0.1.0"
description = "Home infrastructure"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ansible>=12.2.0",
    "python-debian>=1.0.1",
]
